[package]
name = "ff-website-converter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
chrono = "0.4.34"
lazy_static = "1.4.0"
regex = "1.10.3"
serde_json = "1.0.114"
